name: Build fastPathSign
on:
  push:
  workflow_dispatch:
jobs:
  Build-fastPathSign:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install xcodegen
       run: brew install xcodegen
     - name: Generate XCProject
       run: xcodegen generate
     - name: Build App
       run: |
            ls $(pkg-config --cflags libcrypto)
            Scheme="fastPathSign"
            XCProject="fastPathSign.xcodeproj"
            xcodebuild -jobs $(sysctl -n hw.ncpu) -project "$XCProject" -scheme "$Scheme" -configuration Release -arch arm64 -sdk iphoneos -derivedDataPath "$TMPDIR/App" CODE_SIGNING_ALLOWED=NO DSTROOT=$AppTMP/install ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO OTHER_CFLAGS="-fobjc-arc -I$(pkg-config --cflags libcrypto) -Iexternal/include"
            mkdir Payload
            mv "$(echo $TMPDIR/App/Build/Products/Release-iphoneos/*.app)" Payload
            zip -r9 "$Scheme.ipa" Payload
            rm -rf Payload && rm -rf "$TMPDIR/App"